#!/usr/bin/env bash
# generated by pick_days.py --seed 20260805 --days 3
set -euo pipefail
OUT="${1:-replays}"
mkdir -p "$OUT"

echo "=== 2026-06-24  (5516 episodes) ==="
kaggle datasets download -d kaggle/pokemon-tcg-ai-battle-episodes-2026-06-24 -p "$OUT" --unzip

echo "=== 2026-07-18  (4811 episodes) ==="
kaggle datasets download -d kaggle/pokemon-tcg-ai-battle-episodes-2026-07-18 -p "$OUT" --unzip

echo "=== 2026-08-01  (4518 episodes) ==="
kaggle datasets download -d kaggle/pokemon-tcg-ai-battle-episodes-2026-08-01 -p "$OUT" --unzip

echo "downloaded: $(find "$OUT" -name '*.json' | wc -l) json files"
