"""Pick N days at random from the Kaggle episode manifest.

Seeded so the same pick is reproducible: both the baseline run and the
sequence run MUST train on the same replay files, otherwise the tournament
compares data, not designs.

Usage:
    python3 pick_days.py                  # 3 days, seed 20260805
    python3 pick_days.py --days 3 --seed 20260805
    python3 pick_days.py --emit-sh > download_days.sh
"""

import argparse
import csv
import pathlib
import random

HERE = pathlib.Path(__file__).parent
MANIFEST = HERE / "manifest.csv"


def load_rows(path):
    with open(path, newline="", encoding="utf-8") as f:
        return [r for r in csv.DictReader(f) if r.get("date")]


def pick(rows, n, seed):
    rng = random.Random(seed)
    return sorted(rng.sample(rows, n), key=lambda r: r["date"])


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="random day picker")
    ap.add_argument("--manifest", default=str(MANIFEST))
    ap.add_argument("--days", type=int, default=3)
    ap.add_argument("--all", action="store_true",
                    help="take EVERY day in the manifest (bulk mode); "
                         "--days and --seed are ignored")
    ap.add_argument("--seed", type=int, default=20260805)
    ap.add_argument("--emit-sh", action="store_true",
                    help="print a download script instead of a summary")
    ap.add_argument("--emit-list", action="store_true",
                    help="print date<TAB>slug<TAB>episodes, one day per "
                         "line, for scripts that drive the days themselves")
    args = ap.parse_args()

    rows = load_rows(args.manifest)
    if args.all:
        chosen = sorted(rows, key=lambda r: r["date"])
    else:
        chosen = pick(rows, args.days, args.seed)

    if args.emit_list:
        for r in chosen:
            print("%s\t%s\t%s" % (r["date"], r["daily_dataset_slug"],
                                   r["episode_count"]))
    elif args.emit_sh:
        print("#!/usr/bin/env bash")
        print("# generated by pick_days.py "
              + ("--all" if args.all
                 else "--seed %d --days %d" % (args.seed, args.days)))
        print("set -euo pipefail")
        print('OUT="${1:-replays}"')
        print('mkdir -p "$OUT"')
        for r in chosen:
            slug = r["daily_dataset_slug"]
            print(f'\necho "=== {r["date"]}  ({r["episode_count"]} episodes) ==="')
            print(f'kaggle datasets download -d kaggle/{slug} -p "$OUT" --unzip')
        print('\necho "downloaded: $(find "$OUT" -name \'*.json\' | wc -l) json files"')
    else:
        total_ep = sum(int(r["episode_count"]) for r in chosen)
        total_gb = sum(int(r["total_bytes"]) for r in chosen) / 1e9
        print(f"ALL {len(chosen)} days in the manifest" if args.all
              else f"seed={args.seed}  days={args.days} (random)")
        print(f"{'date':<12} {'episodes':>9} {'GB':>7}  slug")
        for r in chosen:
            print(f"{r['date']:<12} {int(r['episode_count']):>9} "
                  f"{int(r['total_bytes'])/1e9:>7.1f}  {r['daily_dataset_slug']}")
        print(f"{'TOTAL':<12} {total_ep:>9} {total_gb:>7.1f}")
